modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="blocks__bits"
version="1.0.0"
displayName="Blocks & Bits"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="jpdal, MCreator"

[[dependencies.blocks__bits]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




